export const ROUTE_PATHS = {
  ROOT: "/",
  LOGIN: "/login",
  REGISTER: "/register",
  DASHBOARD: "/dashboard",
  WORKSPACES: "/workspaces",
  WORKSPACE_INVITATION_ACCEPT: "/workspace-invitations/:token",
  PROJECTS: "/projects",
  MEMBERS: "/members",
  TASKS: "/tasks",
  NOTIFICATIONS: "/notifications",
  CHAT: "/chat",
  REPORTS: "/reports",
  SETTINGS: "/settings",
} as const;
